services:
  api:
    build:
      context: .
      target: api
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"
    init: true

  worker:
    build:
      context: .
      target: worker
    init: true
